name: GPPremium
description: Aplicativo GP.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.1+17

environment:
  sdk: ">=2.11.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path:
  http: ^0.13.4
  flutter_secure_storage: ^3.3.1+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  brasil_fields: ^1.3.0
  date_time_picker: ^2.1.0
  local_auth: ^1.1.10
  http_interceptor: ^1.0.2
  flutter_typeahead: ^3.2.0
  extended_masked_text: ^2.3.0
  flutter_vector_icons: ^1.0.0
  community_material_icon: ^5.9.55
  ionicons: ^0.1.2
  line_icons: ^2.0.1
  equatable: ^2.0.3
  image_picker: ^0.8.4+5
  #image_cropper: ^1.5.1
  permission_handler: ^10.0.0
  usage: ^4.0.2
  flutter_quill:
  rounded_loading_button: ^2.0.9
  printing: ^5.7.2
  intl: ^0.17.0
  open_file: ^3.2.1
  path_provider: ^2.0.2
  url_launcher: ^6.0.6
  device_info_plus: ^3.2.2
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.0.0
  ping_discover_network: ^0.2.0+1
  flutter_barcode_scanner: ^2.0.0
  wifi: ^0.1.5
  flutter_svg: ^0.22.0
  shimmer: ^2.0.0
  dropdown_search: ^1.0.0
  fl_chart: ^0.45.1
  font_awesome_flutter: ^9.1.0
  file_picker: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
   android: true
   ios: true
   background_color: "#000000"    # fundo preto
   adaptive_icon_background: "#000000" # para Android 8+ (fundo do adaptive icon)
   image_path: "assets/images/icone.png"

module:
  androidX: true
