name: GPPremium
description: Aplicativo GP.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.0+15

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  path: ^1.9.0
  http: ^1.1.0
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  equatable: ^2.0.5
  intl: ^0.19.0
  
  # UI & Form dependencies
  brasil_fields: ^1.15.0
  extended_masked_text: ^2.3.1
  font_awesome_flutter: ^9.2.0
  # rounded_loading_button: ^2.0.0  # Removido temporariamente por incompatibilidade
  shimmer: ^3.0.0
  dropdown_search: ^5.0.6
  
  # Icons
  flutter_vector_icons: ^2.0.0
  community_material_icon: ^5.9.55
  ionicons: ^0.2.2
  line_icons: ^2.0.3
  
  # Media & Scanner
  image_picker: ^1.0.7
  mobile_scanner: ^5.2.0
  
  # Permissions & Device
  permission_handler: ^11.3.1
  local_auth: ^2.1.8
  device_info_plus: ^10.1.0
  network_info_plus: ^5.0.0
  
  # Files & Storage
  open_file: ^3.3.2
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  
  # Rich Text Editor (versão compatível com Flutter 3)
  flutter_quill: ^9.4.9
  
  # Charts
  fl_chart: ^0.66.2
  
  # SVG & Images
  flutter_svg: ^2.0.10+1
  
  # Network
  http_interceptor: ^2.0.0
  
  # WiFi (mantendo versão compatível)
  wifi_iot: ^0.3.19
  
  # Printing (versão compatível para impressão fiscal)  
  printing: ^5.9.3
  # esc_pos_printer removido - causava conflitos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
   android: true
   ios: true
   background_color: "#000000"    # fundo preto
   adaptive_icon_background: "#000000" # para Android 8+ (fundo do adaptive icon)
   image_path: "assets/images/icone.png"

module:
  androidX: true
